ci:
  autoupdate_schedule: quarterly
default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.12.0
    hooks:
      - id: stylelint
