ci:
  autoupdate_schedule: quarterly
  skip: [pip-compile]
default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.4
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, -o, requirements.txt]
      - id: pip-compile
        name: pip-compile requirements_dev.in
        args: [requirements_dev.in, -o, requirements_dev.txt]
        files: ^requirements(_dev)?\.(in|txt)$
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.12.0
    hooks:
      - id: stylelint
